# Generated by Django 4.2.7 on 2023-11-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nuarte", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumento",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="instrumentos/"),
        ),
    ]
