# Generated by Django 4.2.7 on 2023-11-22 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nuarte", "0002_alter_instrumento_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_operacao", models.DateTimeField(auto_now_add=True)),
                ("operacao", models.CharField(max_length=100)),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nuarte.instrumento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("ADM", "Administrador"),
                            ("PROF", "Professor"),
                            ("ALUNO", "Aluno"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="user",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="user",
        ),
        migrations.DeleteModel(
            name="Administrador",
        ),
        migrations.DeleteModel(
            name="Aluno",
        ),
        migrations.DeleteModel(
            name="Professor",
        ),
    ]
