# Generated by Django 4.2.7 on 2023-11-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nuarte", "0003_historico_perfil_remove_aluno_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historico",
            name="instrumento",
        ),
        migrations.AddField(
            model_name="instrumento",
            name="historico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nuarte.historico",
            ),
        ),
    ]
