# Generated by Django 4.2.7 on 2023-11-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nuarte", "0004_remove_historico_instrumento_instrumento_historico"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumento",
            name="historico",
        ),
        migrations.RemoveField(
            model_name="instrumento",
            name="imagem",
        ),
        migrations.AddField(
            model_name="historico",
            name="instrumento",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="nuarte.instrumento",
            ),
        ),
    ]
