# Generated by Django 4.2.7 on 2023-11-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nuarte", "0007_historico_devolucao_alter_historico_instrumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="historico",
            name="aprovado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historico",
            name="devolucao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historico",
            name="operacao",
            field=models.CharField(
                choices=[
                    ("S", "Solicitação de instrumento"),
                    ("D", "Devolução de instrumento"),
                ],
                max_length=1,
            ),
        ),
    ]
